# application.yml
--- 
spring: 
  application: 
    name: test

server: 
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8080

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka:8761/eureka/
# leave leaseRenewalIntervalInSeconds and leaseExpirationDurationInSeconds
# unchanged in production
# just here to provide quicker updates to Eureka for demos
  instance: 
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}

words: to,pass,the,test

--- 
spring: 
  profiles: subject
  application: 
    name: subject

words: He,She,Ann,Mary,John,Paul,My dog,My cat
  
--- 
spring: 
  profiles: verb
  application: 
    name: verb

words: likes,loves,hates,dreams,does not like,does not love
  
--- 
spring: 
  profiles: object
  application: 
    name: object

words: beans,cats,dogs,pasta,pizza,pizza margherita,spring,my dog,my cat
