Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network "private_network", ip: "10.11.1.191", virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 80, host: 8081

  config.vm.provision :shell, path: "install-apache.sh"
end
